### ISSUE TITLE
Lat/Lon flipped on Geocode?

### ISSUE THREAD

**Issue by TheOnlyMerlin** [bosth/geofdw#1]
I managed to get this installed on my PostGIS instance and even managed to get the Google geocoder working... with a caveat.  I kept having issues where my points showed up on the map in Antarctica. After some puzzling, it looks like it was because the Lat/Long was in the incorrect order on the points. They should be lon / lat, not lat / lon (See: http://postgis.net/2013/08/18/tip_lon_lat/).

So, when I ran `ST_FlipCoordinates(geom)` on the geometry, everything worked again. 

## Summary
Is the mapping of lat/lon from the Google geocoder in the wrong order? This feels like a pretty dramatic oversight if so. If not, what am I doing wrong?

Python isn't exactly my primary language, but if some code changes are needed, I may be able to do a PR. But I wanted to get the issue up first, so you can have a chance to respond.

Thank you for the work you put into this project! 👍

**Comment by bosth** [comment]
There definitely could be a bug! 

What lat/long were you using that produced the bad geocoding? And if you have the SQL statements that produced the service and the foreign table that would help too.

**Comment by TheOnlyMerlin** [comment]
Server / Foreign Table creation:
```SQL
CREATE SERVER fwd_geocode
  FOREIGN DATA WRAPPER multicorn OPTIONS ( WRAPPER 'geofdw.FGeocode' );

CREATE FOREIGN TABLE public.fgc_google ( query TEXT, rank INTEGER, address TEXT, geom GEOMETRY )
SERVER fwd_geocode
OPTIONS (api_key 'abcdefghijklmnopqrst-uvwxyz1234567890AB');
```

Then here is an example query and it's matching data. I tried to make it as self-contained as I could:
``` sql
SELECT
  label,
  st_astext(geocoded.wkb_geometry) AS wkt,
  st_srid(geocoded.wkb_geometry)   AS srid,
  st_y(wkb_geometry)               AS geocoded_lat,
  actual_lat,
  st_x(wkb_geometry)               AS geocoded_lon,
  actual_lon,
  address,
  wkb_geometry
FROM (
  SELECT
    *,
    (
      SELECT google.geom
      FROM public.fgc_google AS google
      WHERE google.query = locations.address
      LIMIT 1
    ) AS wkb_geometry
  FROM (
         SELECT
           unnest(ARRAY ['The White House', 'NYSE'])
             AS label,
           unnest(ARRAY ['1600 Pennsylvania Ave NW, Washington, DC 20500', '11 Wall St, New York, NY 10005'])
             AS address,
           unnest(ARRAY [38.8977213, 40.706877])
             AS actual_lat,
           unnest(ARRAY [-77.0368969, -74.0134541])
             AS actual_lon
       ) AS locations
) AS geocoded;
```

Results in....

label | wkt | srid | geocoded_lat | actual_lat | geocoded_lon | actual_lon | address | wkb_geometry
----- | --- | ---- | ------------ | ---------- | ------------ | ---------- | ------- | ------------
The White House | POINT Z (38.8976633 -77.0365739 0) | 4326 | -77.0365739 | 38.8977213 | 38.8976633 | -77.0368969 | 1600 Pennsylvania Ave NW, Washington, DC 20500 | 01010000A0E6100000E3288AA1E6724340C7180E3A574253C00000000000000000
NYSE | POINT Z (40.7068661 -74.0113189 0) | 4326 | -74.01131889999999 | 40.706877 | 40.7068661 | -74.0134541 | 11 Wall St, New York, NY 10005 | 01010000A0E610000056139F967A5A4440E854E872B98052C00000000000000000

If my example is correct, it seems like the lat / lon should be swapped. Does this track?

**Comment by bosth** [comment]
Thanks @TheOnlyMerlin, you are absolutely correct. The geocoder foreign data wrapper was interpreting the queries correctly but was constructing the geometry object afterwards incorrectly with inverted coordinates. I will push a fix shortly.

**Comment by TheOnlyMerlin** [comment]
Sweet, thank you!
